server:
  port: 0

spring:
  application:
    name: ms-pagamentos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pagamentos
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:

      httpclient:
        enabled: true
        max-connections: 200
        max-connections-per-route: 50
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
          ms-pedidos:
            loggerLevel: full
            connectTimeout: 10000
            readTimeout: 10000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    io.github.nivaldosilva.ms_pagamentos.client: DEBUG
    feign: DEBUG
    org.apache.http: DEBUG