server:
    port: 0

spring:
  application:
    name: ms-pedidos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pedidos
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true 
    hostname: localhost

